### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by SamBurkart** [rajatsen91/CCIT#2]
Import of CCIT in Jupyter (after installing with pip install ccit) throws an error:

ModuleNotFoundError: No module named 'DataGen'

**Comment by karthikeyansh** [comment]
Thanks for reporting this. We will get back to you soon.

Does it work with just an editor and running it in native python ?

**Comment by rajatsen91** [comment]
I just installed CCIT on a fresh virtual environment in order to check the working. Here are the steps I followed:

1.Install virtualenv (if it is not installed already)
2. virtualenv ~/testing
3. source ~/testing/bin/activate
4. pip install CCIT

After this I opened python, and import seems to work fine. I tested it in jupyter notebook as well. Please let me know if the issue is only in native python or in jupyter notebook?  Also can you please try : from CCIT import *
